app1/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *

urlpatterns = patterns('app1.views',
    (r'^$', 'index'),
    (r'^sitemap.xml$', 'sitemap'),
    (r'^rss.xml$', 'rsslatest'),
    (r'^index.xml$', 'rsslatest'),
    (r'^category/(?P<keyid>.+)/(?P<name>.+)$', 'category_article'),
    (r'^tag/(?P<tag>.+)$', 'tag_article'),
    #
    (r'^add_article$', 'add_article'),
    (r'^article/(?P<keyid>.+)/(?P<title>.+)$', 'show_article'),
    (r'^a/(?P<keyid>.+)$', 'show_article_short'),
    (r'^edit_article/(?P<key>.+)$', 'edit_article'),
    (r'^del_article/(?P<key>.+)$', 'del_article'),
    (r'^lastcomments$', 'lastcomments'),
    (r'^del_comment/(?P<key>.+)$', 'del_comment'),
    (r'^emptymem$', 'emptymem'),
    (r'^profile$', 'profile'),
    (r'^profile/(?P<key>.+)$', 'show_profile'),
    (r'^myarticles$', 'myarticles'),
)

registration/urls.py
"""
URLConf for Django user registration and authentication.

If the default behavior of the registration views is acceptable to
you, simply use a line like this in your root URLConf to set up the
default URLs for registration::

    (r'^accounts/', include('registration.urls')),

This will also automatically set up the views in
``django.contrib.auth`` at sensible default locations.

But if you'd like to customize the behavior (e.g., by passing extra
arguments to the various views) or split up the URLs, feel free to set
up your own URL patterns for these views instead. If you do, it's a
good idea to use the names ``registration_activate``,
``registration_complete`` and ``registration_register`` for the
various steps of the user-signup process.

"""


from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib.auth import views as auth_views

from registration.views import activate
from registration.views import register


urlpatterns = patterns('',
                       # Activation keys get matched by \w+ instead of the more specific
                       # [a-fA-F0-9]{40} because a bad activation key should still get to the view;
                       # that way it can return a sensible "invalid key" message instead of a
                       # confusing 404.
                       url(r'^activate/(?P<activation_key>\w+)/$',
                           activate,
                           name='registration_activate'),
                       url(r'^login/$',
                           auth_views.login,
                           {'template_name': 'registration/login.html'},
                           name='auth_login'),
                       url(r'^logout/$',
                           auth_views.logout,
                           name='auth_logout'),
                       url(r'^password/change/$',
                           auth_views.password_change,
                           name='auth_password_change'),
                       url(r'^password/change/done/$',
                           auth_views.password_change_done,
                           name='auth_password_change_done'),
                       url(r'^password/reset/$',
                           auth_views.password_reset,
                           name='auth_password_reset'),
                       url(r'^password/reset/confirm/(?P<uidb36>.+)/(?P<token>.+)/$',
                           auth_views.password_reset_confirm,
                           name='auth_password_reset_confirm'),
                       url(r'^password/reset/complete/$',
                           auth_views.password_reset_complete,
                           name='auth_password_reset_complete'),
                       url(r'^password/reset/done/$',
                           auth_views.password_reset_done,
                           name='auth_password_reset_done'),
                       url(r'^register/$',
                           register,
                           name='registration_register'),
                       url(r'^register/complete/$',
                           direct_to_template,
                           {'template': 'registration/registration_complete.html'},
                           name='registration_complete'),
                       )

urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from ragendja.urlsauto import urlpatterns
from ragendja.auth.urls import urlpatterns as auth_patterns
#from myapp.forms import UserRegistrationForm
from django.contrib import admin

admin.autodiscover()

handler500 = 'ragendja.views.server_error'

urlpatterns = auth_patterns + patterns('',
    ('^admin/(.*)', admin.site.root),
    (r'^$', 'app1.views.index'),
    (r'^robots.txt$', 'app1.views.robots'),
    #(r'^$', 'django.views.generic.simple.direct_to_template',{'template': 'main.html'}),
    # Override the default registration form
    #url(r'^account/register/$', 'registration.views.register',kwargs={'form_class': UserRegistrationForm},name='registration_register'),
) + urlpatterns

app1/forms.py
# -*- coding: utf-8 -*-
from django import forms
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _, ugettext as __
from app1.models import Category,Entry,Comment,Profile,Links
import re

class CategoryForm(forms.ModelForm):
    def cleaned_data(self):
        memcache.delete("key_all_categories")
        return self.cleaned_data
    
    class Meta:
        exclude = ['entrycount','post_keys']
        model = Category

class EntryForm(forms.ModelForm):
    title = forms.CharField(required = True,widget=forms.widgets.Input(attrs={'style':"width:500px;padding:4px;"}), max_length=50, label=_(u'Title'))
    content = forms.CharField(required = True,widget=forms.widgets.Textarea(attrs={'style':"width:600px;height:400px;",'rows': 22,'cols': 75,'class':'tinymce'}), max_length=10000, label=_(u'Content'))
    abstract = forms.CharField(required = False,widget=forms.widgets.Textarea(attrs={'style':"width:540px;height:60px;border:1px solid #999999;"}), max_length=300, label=_(u'Abstract'),help_text=_(u'Max length 300s'))
    slug = forms.CharField(required = False,widget=forms.widgets.Input(attrs={'style':"width:500px;padding:4px;"}), max_length=60, label=_(u'slug'))
        
    class Meta:
        exclude = ['author','tags','prev_key','next_key','pub_time','commentcount','comment_keys']
        model = Entry

class CommentForm(forms.ModelForm):
    name = forms.CharField(required = True,widget=forms.widgets.Input(attrs={'class':"text"}), max_length=20, label=_(u'Name'))
    message = forms.CharField(required = True,widget=forms.widgets.Textarea(attrs={'style':"width:500px;height:100px;"}), max_length=300, label=_(u'Message'),help_text=_(u'Max length 300s'))
    web = forms.URLField(required = False,widget=forms.widgets.Input(attrs={'class':"text"}), max_length=150 , label=_(u'Web'), help_text=_(u'ex: http://www.google.com'))
    
    def clean(self):
        message = self.cleaned_data.get('message','')
        if message:
            message = message.replace("<script","< script")
            message = message.replace("</script>","< /script>")
            p = re.compile( '[\n\r]{2,}')
            message = p.sub( '\n', message)             
            message = message.replace("\n","<br/>")
        self.cleaned_data['message'] = message
        return self.cleaned_data
        
    class Meta:
        exclude = ['entry','date','email','gravatar']
        model = Comment

class ProfileForm(forms.ModelForm):
    displayname = forms.CharField(required = True,widget=forms.widgets.Input(attrs={'class':"text"}), max_length=15, label=_(u'Display name'))
    web = forms.URLField(required = False,widget=forms.widgets.Input(attrs={'class':"text"}), max_length=150 , label=_(u'Web'), help_text=_(u'ex: http://www.google.com'))
    aboutme = forms.CharField(required = False,widget=forms.widgets.Textarea(attrs={'style':"width:300px;height:100px;"}), max_length=300, label=_(u'About me'),help_text=_(u'Max length 300s'))
    signtext = forms.CharField(required = False,widget=forms.widgets.Input(attrs={'class':"text"}), max_length=50, label=_(u'Sign text'),help_text=_(u'Max length 50s'))
    #art_left = forms.CharField(required = False,widget=forms.widgets.Textarea(attrs={'style':"width:300px;height:100px;"}), max_length=300, label=_(u'Article top_left ads'),help_text=_(u'Put your Google AdSense to your articles top_left, Formats : 300 x 250 is required and Image Only is best.'))
    #art_right = forms.CharField(required = False,widget=forms.widgets.Textarea(attrs={'style':"width:300px;height:100px;"}), max_length=300, label=_(u'Article top_right ads'),help_text=_(u'Put your Google AdSense to your articles top_right, Formats : 300 x 250 is required and Text Only is best.'))
    
    class Meta:
        exclude = ['author','email','pub_ads','art_left','art_right','gravatar']
        model = Profile

class LinksForm(forms.ModelForm):
    def cleaned_data(self):
        memcache.delete("links_key")
        return self.cleaned_data
    
    class Meta:
        model = Links

app1/templates/app1/add_article.html
{% extends 'app1/base.html' %}
{% load i18n %}
{% block subtitle %}{% if obj %}{% trans 'Apply changes' %}{% else %}{% trans 'Create' %}{% endif %}{% endblock %}

{% block content_main %}
<!-- Load jQuery -->
<script type="text/javascript" src="{%if g_blog.googlejquery%}{{g_blog.googlejquery|safe}}{%else%}/media/js/jquery.min.js{%endif%}"></script>

<!-- Load TinyMCE -->
<script type="text/javascript" src="/tiny_mce/jquery.tinymce.js"></script>
<script type="text/javascript">
	$().ready(function() {
		$('textarea.tinymce').tinymce({
			// Location of TinyMCE script
			script_url : '/tiny_mce/tiny_mce.js',

			// General options
			theme : "advanced",
			plugins : "pagebreak,table,advhr,advimage,advlink,iespell,inlinepopups,insertdatetime,preview,media,searchreplace,contextmenu,directionality,noneditable,visualchars,nonbreaking,xhtmlxtras",

			// Theme options
			theme_advanced_buttons1 : "bold,italic,underline,strikethrough,|,justifyleft,justifycenter,justifyright,justifyfull,formatselect,fontsizeselect,nonbreaking,advhr,|,ltr,rtl",
			theme_advanced_buttons2 : "replace,|,bullist,numlist,|,outdent,indent,blockquote,|,undo,redo,|,link,unlink,anchor,image,cleanup,code,|,insertdate,inserttime,preview,|,forecolor,backcolor",
			theme_advanced_buttons3 : "tablecontrols,|,hr,removeformat,visualaid,|,sub,sup,|,charmap,iespell,media",
			theme_advanced_toolbar_location : "top",
			theme_advanced_toolbar_align : "left",
			theme_advanced_statusbar_location : "bottom",
			theme_advanced_resizing : true,
			
			// Example content CSS (should be your site CSS)
			content_css : "/media/css/content.css",
						
			// Replace values for the template plugin
			template_replace_values : {
				username : "Some User",
				staffid : "991234"
			}
		});
	});
</script>
<!-- /TinyMCE -->

<div class="yui-b">
<div class="yui-g" id="articletop">
<!-- YOUR DATA GOES HERE -->
<h2>{% if obj %}{% trans "Edit" %}{% else %}{% trans "Add" %}{% endif %} {% trans "Article" %}</h2>
<div id="contenct">

<form action="" method="post" enctype="multipart/form-data" id="form1">
    {% if form.errors %}
    <p style="color: red;">{% trans "Please correct the error " %}</p>
    {% endif %}
    <p>{% if form.category.errors %}{{form.category.errors}}<br/>{% endif %}{{ form.category.label }} : {{ form.category }} {% trans "*required" %}</p>
    <p>{% if form.title.errors %}{{form.title.errors}}<br/>{% endif %}{{ form.title.label }} : {{ form.title }} {% trans "*required" %}</p>
    <p>{% if form.content.errors %}{{form.content.errors}}<br/>{% endif %}{{ form.content.label }} : {% trans "*required" %}</p>
    <p>{{ form.content }}</p>
    <p>{% trans "Tags" %} : <input name="tags" type="text" value="{{ tags }}" size="60" maxlength="60" style="width:400px;padding:4px;"/> split with ","</p>
    <p>{% if form.abstract.errors %}{{form.abstract.errors}}<br/>{% endif %}{{ form.abstract.label }} : {{ form.abstract.help_text }}</p>
    <p>{{ form.abstract }}</p>
    <p>{% if form.slug.errors %}{{form.slug.errors}}<br/>{% endif %}{{ form.slug.label }} : {{ form.slug }}</p>
	<p>{{ form.commentclosed.label }} : {{ form.commentclosed }}</p>
    <p><input type="submit" value=" {% if obj %}{% trans 'Apply changes' %}{% else %}{% trans 'Create' %}{% endif %} " />
	</p>
    
<br />

</form>


</div>
</div>
</div>

{% endblock %}

app1/templates/app1/articlelist.html
{% extends 'app1/base.html' %}
{% load i18n %}
{% block subtitle %}{{obj}}{% endblock %}

{% block extra-head %}
<meta name="keywords" content="{{obj}},{{ g_blog.title }},{{ g_blog.keywords }}" />
<meta name="description" content="{{obj}},{{ g_blog.description }}" />
{% endblock %} 

{% block content_main %}
<div class="yui-b">
<div class="yui-g" id="artlist_top">
    <h2 title="{{obj|safe}}">{{obj|safe}}</h2>
    {%if ads_articlelist_top%}<div class="artlist_ggad">{{ads_articlelist_top|safe}}</div>{%endif%}
</div>

<div class="yui-g">

<div id="con_articlelist">
<ul>
{%for each in cur_articlelist%}{%if each%}
<li>
<h3><a href="{{each.get_absolute_url}}" title="{{each.title|safe}}">{{each.title|safe}}</a></h3>
<p>{% trans "Categories" %} <a href="{{each.category.get_absolute_url}}" title="{{each.category.name}}">{{each.category.name|safe}}</a> {%if each.tags%}{% trans "Tags" %}: {%for tag in each.tags%}<a href="{% url app1.views.tag_article tag %}" title="{{tag}}">{{tag}}</a>{% if not forloop.last %}, {% endif %}{%endfor%}{%endif%} {% trans "Author" %}: <a href="{{each.profile.get_absolute_url}}" title="{{each.profile.displayname|safe}} {% trans 'Profile' %}">{{each.profile.displayname|safe}}</a> {% trans "Date" %}: {{each.pub_time|date:"d/m/Y"}}</p>
<p>{{each.abstract|safe}}</p>
<p class="more"><a href="{{each.get_absolute_url}}" rel="nofollow">{% trans "Read more" %}</a></p>
</li>{%endif%}{%endfor%}
</ul>
{%if pagination_div%}{{ pagination_div|safe }}{%endif%}
</div>

</div>

</div>

{% endblock %}

app1/templates/app1/base.html
{% extends 'base.html' %}
{% load cache %}
{% load i18n %}
{% block title %}{% block subtitle %}{% endblock %} - GAE cms{% endblock %}

{% block nav %}
    <li class="curselect"><a href="{% url app1.views.index %}" title="GAE CMS">GAE CMS</a></li>
    <li><a href="http://gaebbs.xibu.biz/" title="GAE {% trans 'BBS' %}">GAE {% trans 'BBS' %}</a></li>
{% endblock %}

{% block content %}
<div id="yui-main">
    {% block content_main %}{% endblock %}
</div>

<div class="yui-b" id="sidebar">
<form action="http://www.google.com/cse" target="_blank" id="cse-search-box">
  <div>
    <input type="hidden" name="cx" value="{% if g_blog.google_cse_cx %}{{g_blog.google_cse_cx|safe}}{% else %}009677936332633277893:-nyho-cdiwa{% endif %}" />
    <input type="hidden" name="ie" value="UTF-8" />
    <input type="text" name="q" size="28" />
    <input type="submit" name="sa" value="{% trans 'Go' %}" />
  </div>
</form>

{% if user.is_authenticated %}
<div class="wrap_top">
<h2>{% trans "Administration" %}</h2>
<ul class="wrap_list">
<li><a href="{% url app1.views.add_article %}">{% trans "Add Article" %}</a></li>
<li><a href="{% url app1.views.myarticles %}">{% trans "My articles" %}</a></li>
{% if user.is_superuser %}
<li><a href="{% url app1.views.lastcomments %}">{% trans "Recent comments" %}</a></li>
<li><a href="/admin/app1/">{% trans "Django administration" %}</a></li>
{%endif%}
</ul>
</div>
{%endif%}

<div class="wrap_top">
<h2>{% trans "Category List" %}</h2>
<ul class="wrap_list">
{%for each in all_categories%}
<li><a href="{{each.get_absolute_url}}" title="{{each.name|safe}}">{{each.name|safe}}</a></li>{%endfor%}
</ul>
</div>

{%if g_blog.display_ngp%}
<div class="wrap_top">
<h2>{% trans "NGP Photo of day" %}</h2>
{% cache 600 ngp %}
<p style="text-align:center;">
<a href="http://www.national-geographic-photo.com/" target="_blank" title="{% trans 'Click here to view full size' %}">
<img src='http://www.national-geographic-photo.com/showimg' alt="{% trans 'NGP Photo of day' %}" width="200" height="150" style="BORDER-TOP-STYLE: none; BORDER-RIGHT-STYLE: none; BORDER-LEFT-STYLE: none; BORDER-BOTTOM-STYLE: none;" /></a>
</p>
{% endcache %}
</div>
{%endif%}

{%if newcomment_list%}
<div class="wrap_top">
<h2>{% trans "Recent Comment" %}</h2>
<ul class="wrap_list">
{%for each in newcomment_list%}
<li class="comment">{{each.name}}@<a href="{{each.entry.get_absolute_url}}#{{each.key.id}}" title='{{each.message|slice:":100"}}' target="_blank">{{each.entry.title|safe}}</a></li>{%endfor%}
</ul>
</div>
{%endif%}

{%if links_list%}
<div class="wrap_top">
<h2>{% trans "Links" %}</h2>
<ul class="wrap_list">
{%for each in links_list%}
<li class="link"><a href="{{each.url}}" title="{{each.name}}" target="_blank" rel="nofollow">{{each.name}}</a></li>{%endfor%}
</ul>
</div>
{%endif%}

</div>

{% endblock %}

app1/templates/app1/delete_article.html
{% extends 'app1/base.html' %}
{% load i18n %}
{% block subtitle %}{% trans "Confirm Delete" %}{% endblock %}

{% block content_main %}
<div class="yui-b">

<div class="yui-g" id="articletop">
<h2>{% trans "Confirm Delete" %}</h2>
<div id="contenct">
<div class="notice">
<form action="{{ request.path }}" method="post">
    <ul>
    <li>{% trans "You want delete" %} <strong>{{obj.title}}</strong>?</li>
    <li>{{obj.abstract}}</li>
    <li>{{obj.author}}</li>
    <li>{{obj.category}}</li>
    <li></li>
    </ul>
  <input type="submit" value="{% trans 'Delete' %}" />
</form>
</div>

</div>
</div>

</div>

{% endblock %}

app1/templates/app1/detail.html
{% extends 'app1/base.html' %}
{% load i18n %}
{% block subtitle %}{{obj}}{% endblock %}

{% block extra-head %}
<meta name="keywords" content="{{obj}},{{obj.strtags}},{{ g_blog.title }},{{ g_blog.keywords }}" />
<meta name="description" content="{{obj}},{{obj.category.name}},{{obj.strtags}},{{obj.abstract}}" />
{% endblock %} 

{% block content_main %}
<div class="yui-b">

<div class="yui-g" id="articletop">
<h2><a href="{{obj.category.get_absolute_url}}" title="{{obj.category.name|safe}}">{{obj.category.name|safe}}</a> &raquo; <span title="{{obj.title|safe}}">{{obj.title|safe}}</span></h2>

{% if obj.profile.pub_ads %}
<div class="yui-u first" id="ggad_index">
{{obj.profile.art_left|safe}}
</div>
<div class="yui-u" id="ggad_index2">
{{obj.profile.art_right|safe}}
</div>
{% else %}
{%if ads_articledetail_left_top%}<div class="yui-u first" id="ggad_index">
{{ads_articledetail_left_top|safe}}
</div>{%endif%}
{%if ads_articledetail_right_top%}<div class="yui-u" id="ggad_index2">
{{ads_articledetail_right_top|safe}}
</div>{%endif%}
{%endif%}

<div class="clear"></div>
<div id="contenct">
{{obj.content|safe}}
<p class="permalink">{% trans "Permalink" %} http://{{current_site.domain}}{{obj.short_url}}</p>
<p>{% trans "Categories" %} <a href="{{obj.category.get_absolute_url}}" title="{{obj.category.name|safe}}">{{obj.category.name|safe}}</a> {%if obj.tags%}{% trans "Tags" %}: {%for tag in obj.tags%}<a href="{% url app1.views.tag_article tag %}" title="{{tag}}">{{tag}}</a>{% if not forloop.last %}, {% endif %}{%endfor%}{%endif%} {% trans "Author" %}: <a href="{{obj.profile.get_absolute_url}}" title="{{obj.profile.displayname|safe}} {% trans 'Profile' %}" rel="nofollow">{{obj.profile.displayname|safe}}</a> {% trans "Date" %} {{obj.pub_time|date:"d/m/Y"}}</p>
<ul> 
	{% if obj.next %}<li>{% trans "Newer Post" %}: <a href="{{obj.next.get_absolute_url}}" title="{{obj.next.title}}">{{obj.next.title}}</a></li>{% endif %}
	{% if obj.prev %}<li>{% trans "Older Post" %}: <a href="{{obj.prev.get_absolute_url}}" title="{{obj.prev.title}}">{{obj.prev.title}}</a></li>{% endif %}
</ul>
{% if user.is_authenticated %}
<p>{% if user.is_superuser %}
{% trans "Administration" %}: <a href='{% url app1.views.edit_article key=obj.key %}'>{% trans "Edit" %}</a>
| <a href='{% url app1.views.del_article key=obj.key %}'>{% trans "Delete" %}</a>
{%else%}
{% ifequal user obj.author %}
{% trans "Author" %}: <a href='{% url app1.views.edit_article key=obj.key %}'>{% trans "Edit" %}</a>
{% endifequal %}
{% endif %}</p>
{% endif %}

{%if not obj.commentclosed%}
<a name="postcomment"></a>

<hr/>
<h3>{% trans "Like what you read?" %} 
{% if user.is_authenticated %}
<script language="javascript" type="text/javascript">  
//
function show_post_comment(){
    document.getElementById("postcomment2").style.display = "block";
}
//
function replyto(somebd,commentkey){
    show_post_comment();
	document.getElementById("id_toID").value = commentkey;
    document.getElementById("id_message").value = "To "+somebd+":\n";
}
</script> 
<a href="#postcomment" onclick='show_post_comment();'>{% trans "Leave a comment" %}</a>
{%else%}
<a href="{{continue_url}}">{% trans "Secure login with google account" %}</a> {% trans "Leave a comment" %}
{%endif%}
</h3>

<div id="postcomment2" {%if not form.name.data%}style="display:None;"{%endif%}>

<form action="" method="POST">
<INPUT type="hidden" id="id_toID" name="toID" value="">
<p>{%if form.name.errors%}{{form.name.errors}}<br/>{%endif%}<label for="id_name">{{form.name.label}}: </label> {{form.name}} {% trans "*required" %}<br/>
{%if form.web.errors%}{{form.web.errors}}<br/>{%endif%}<label for="id_web">{{form.web.label}}: </label> {{form.web}} {{form.web.help_text}}<br/>
{%if form.message.errors%}{{form.message.errors}}<br/>{%endif%}<label for="id_message">{{form.message.label}}: {% trans "*required" %} ({{form.message.help_text}})</label> <br/>{{form.message}} </p>

<p><input type="submit" style="width: 90px" value="{% trans 'Submit' %}" /></p>
</form>

</div>
{%endif%}

</div>
</div>

<div class="yui-g" id="articlebot">
    <div class="yui-u first cate">
    <h2>{% trans "Related articles" %}</h2>
    <ul class="odd">{%for each in obj.relateposts%}<li><a href="{{each.get_absolute_url}}" title="{{each.title}}">{{each.title}}</a></li>{%endfor%}
    </ul>    
    </div>
    
    <div class="yui-u cate">
    <h2><a href="{{obj.category.get_absolute_url}}" title="{{obj.category.name|safe}}">{{obj.category.name|safe}}</a></h2>
    <ul class="even">{%for each in obj.category.posts%}<li><a href="{{each.get_absolute_url}}" title="{{each.title}}">{{each.title}}</a></li>{%endfor%}
    </ul>    
    </div>
</div>
{%if commentlist%}
<a name="comments"></a>
<div class="yui-g" id="articletop">
<h2>{% trans "Comments" %}</h2>
<ul class="comments">
{%for each in commentlist%}
<li><a name="{{ each.key.id }}"></a> 
<h3 class="messageh3" title="{{each.name}}"><img src="{{each.gravatar_url}}" class="gravatar" alt="{{each.name}}" height="60" width="60" /></h3>
<p class="message">
{%if each.web%}<a href="{{each.web}}" title="{{each.web}}" target="_blank" rel="nofollow">{{each.name}}</a>
{%else%}
{{each.name}}
{%endif%}
@{{each.date|date:"Y-m-d H:i:s"}} {%if not obj.commentclosed%}<a href="#postcomment" onclick='replyto("{{each.name}}","{{each.key}}");' title="{% trans 'Reply' %} {{each.name}}">{% trans "Reply" %}</a>{%endif%} {% if user.is_superuser %} | <a href='{% url app1.views.del_comment key=each.key %}'>{% trans "Delete" %}</a>{%endif%}<br/>
{{each.message|safe}}</p>
</li>{%endfor%}
</ul>
{%if pagination_div%}{{ pagination_div|safe }}{%endif%}
</div>
{%endif%}
</div>

{% endblock %}

app1/templates/app1/index.html
{% extends 'app1/base.html' %}
{% load i18n %}
{% block subtitle %}{{ g_blog.title }}{% endblock %}

{% block extra-head %}
<meta name="keywords" content="{{ g_blog.title }},{{ g_blog.keywords }}" />
<meta name="description" content="{{ g_blog.description }}" />
{% endblock %} 

{% block content_main %}
<div class="yui-b" id="conmain_index">
<div class="yui-g">
    <div class="yui-u first" id="ggad_index">
    {%if ads_index_left_top%}{{ads_index_left_top|safe}}{%endif%}
    </div>
    <div class="yui-u cate">
    <h2>{% trans "Recent posts" %} <A title="{% trans 'RSS Feed' %}" href="{% url app1.views.rsslatest%}" target="_blank"><IMG title="{% trans 'RSS Feed' %}" src="/media/images/rss.gif" alt="{% trans 'RSS Feed' %}"></A></h2>
    <ul class="even">{%for each in newposts%}<li><a href="{{each.get_absolute_url}}" title="{{each.title}}">{{each.title}}</a></li>{%endfor%}
    </ul>
    </div>
</div>
<div class="yui-g">
{%for cate in all_categories|slice:":8"%}
{% if forloop.counter|divisibleby:2 %}
    <div class="yui-u cate">
    <h2><a href="{{cate.get_absolute_url}}" title="{{cate.name|safe}}">{{cate.name|safe}}</a></h2>
    <ul class="odd">{%for each in cate.posts%}<li><a href="{{each.get_absolute_url}}" title="{{each.title}}">{{each.title}}</a></li>{%endfor%}
    </ul>    
    </div>
    <div class="clear"></div>
{%else%}
    <div class="yui-u first cate">
    <h2><a href="{{cate.get_absolute_url}}" title="{{cate.name|safe}}">{{cate.name|safe}}</a></h2>
    <ul class="even">{%for each in cate.posts%}<li><a href="{{each.get_absolute_url}}" title="{{each.title}}">{{each.title}}</a></li>{%endfor%}
    </ul>    
    </div>    
{%endif%}
{%endfor%}
</div>

</div>

{% endblock %}

app1/templates/app1/tip.html
{% extends 'app1/base.html' %}
{% load i18n %}
{% block subtitle %}{% trans "Message" %}{% endblock %}

{% block content_main %}
<div class="yui-b">

<div class="yui-g" id="articletop">
<h2>{% trans "Message" %}</h2>
<div id="contenct">
<div class="notice">{{tip|safe}}</div>
</div>
</div>

</div>

{% endblock %}